/PhysicsList/RegisterPhysics G4EmStandardPhysics_option4
/PhysicsList/RegisterPhysics G4EmExtraPhysics
/PhysicsList/RegisterPhysics G4DecayPhysics
/PhysicsList/RegisterPhysics G4RadioactiveDecayPhysics
/PhysicsList/RegisterPhysics G4HadronElasticPhysicsHP
/PhysicsList/RegisterPhysics G4HadronPhysicsQGSP_BERT_HP
/PhysicsList/RegisterPhysics G4StoppingPhysics
/PhysicsList/RegisterPhysics G4IonPhysics
/PhysicsList/RegisterPhysics G4OpticalPhysics
/PhysicsList/RegisterPhysics NexusPhysics
/PhysicsList/RegisterPhysics G4StepLimiterPhysics
#/PhysicsList/RegisterPhysics QGSP_BERT_HP

/process/optical/scintillation/setFiniteRiseTime true

/nexus/RegisterGeometry HyperAr

/nexus/RegisterGenerator HyperonGenerator #ScintillationGenerator

/nexus/RegisterPersistencyManager PersistencyManager

# full optical build
#/nexus/RegisterRunAction      DefaultRunAction
#/nexus/RegisterEventAction    SaveAllEventAction
#/nexus/RegisterTrackingAction OpticalTrackingAction

# default build
/nexus/RegisterRunAction      DefaultRunAction
/nexus/RegisterEventAction    DefaultEventAction
/nexus/RegisterTrackingAction DefaultTrackingAction

/nexus/RegisterMacro macros/HyperAr.config.mac
