/nexus/random_seed 123425

/control/verbose  0
/run/verbose      0
/event/verbose    0
/tracking/verbose 0

#/Generator/ScintGenerator/region CENTRAL_AXIS
#/Generator/ScintGenerator/nphotons 1


/Generator/HyperonGenerator/inputFile ../../../4_Simulations/HyperonsArgon/generators_qe/FSILambda_muon_events_6.dat
/Generator/HyperonGenerator/position 0. 0. 1. #-6000 #-4850.


/control/execute macros/physics/IonizationElectron.mac

/nexus/persistency/outputFile output/hyperar_QE_FSI_lar_V3.0
