/nexus/random_seed 123425

/Generator/SingleParticle/particle proton
/Generator/SingleParticle/min_energy  <energy> #2GeV is mpv for mu exiting LAr according to cdr pg 102
/Generator/SingleParticle/max_energy  <energy>

#/Generator/SingleParticle/position 0. 0. -1.

/Generator/SingleParticle/position 0. 0. 1. #-6000 #-4850.
#/Generator/SingleParticle/momentum 0. 0. 1.

#/Generator/SingleParticle/min_costheta 
#/Generator/SingleParticle/max_costheta 
#/Generator/SingleParticle/min_phi 
#/Generator/SingleParticle/max_phi 
/Generator/SingleParticle/region CENTER

#/Generator/ScintGenerator/region CENTRAL_AXIS
#/Generator/ScintGenerator/nphotons 1

/control/execute macros/physics/IonizationElectron.mac

/nexus/persistency/outputFile <outdir>/ndgarsimple_hermeticity_ss10mm_proton_<f_id>_centre